### ISSUE TITLE
Run CI tests against newer versions of Nodejs

### ISSUE THREAD

**Issue by franz-josef-kaiser** [wecodemore/grunt-githooks#51]
Currently [our _Travis CI_ setup](https://github.com/wecodemore/grunt-githooks/blob/10ae30c4564a88e963f9629f4fb10608adc965fb/.travis.yml) only runs against Nodejs 0.10. We should test against newer versions as well:

```yml
language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
```
